# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk
from tkinter import ttk, messagebox


# Adicionar o diretório raiz do projeto ao sys.path para importar módulos
# Resolve para a pasta do projeto (`doacao_animal_python`) mesmo quando
# o arquivo é executado diretamente como `python ui/login.py`.
project_root = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from DAO.login_dao import LoginDAO
from exceptions.custom_exception import CustomException
from repository.mysql_connection import MYSQLConnection

def load_asset(path):
    base = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))  # ui directory
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

class Login(tk.Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.controller = controller

        # Estilos suaves com ttk
        style = ttk.Style(self)
        style.theme_use('clam')
        style.configure('Card.TFrame', background='#E9ECEF')
        style.configure('Heading.TLabel', background='#E9ECEF', font=('Segoe UI', 20, 'bold'), foreground='#222')
        style.configure('Label.TLabel', background='#E9ECEF', font=('Segoe UI', 12), foreground='#111')
        style.configure('TEntry', padding=6)
        style.configure('Accent.TButton', background="#4B6EF6", foreground='white', font=('Segoe UI', 12, 'bold'))
        style.map('Accent.TButton',
              background=[('active', '#3751c8'), ('pressed', '#2d43a6'), ('!active', '#4B6EF6')],
              foreground=[('disabled', '#bdbdbd'), ('!disabled', 'white')])

        # Painel principal com aparência suave
        self.painel_principal = ttk.Frame(self, style='Card.TFrame')
        self.painel_principal.pack(fill=tk.BOTH, expand=True, padx=24, pady=20)

        # Configurar grid
        self.painel_principal.grid_rowconfigure(0, weight=0)
        self.painel_principal.grid_rowconfigure(1, weight=0)
        self.painel_principal.grid_rowconfigure(2, weight=0)
        self.painel_principal.grid_rowconfigure(3, weight=0)
        self.painel_principal.grid_rowconfigure(4, weight=0)
        self.painel_principal.grid_columnconfigure(0, weight=0)
        self.painel_principal.grid_columnconfigure(1, weight=1)
        self.painel_principal.grid_columnconfigure(2, weight=1)

        # Label logo (row 0, col 1)
        self.label_logo = ttk.Label(self.painel_principal, text="Logo", style='Heading.TLabel')
        self.label_logo.grid(row=0, column=1, columnspan=2, pady=(0, 18), sticky='ew')

        # Carregar logo se existir
        logo_img = None
        fname = "logo.jpg"
        path = load_asset(fname)
        if os.path.exists(path):
            try:
                logo_img = tk.PhotoImage(file=path)
            except Exception:
                try:
                    from PIL import Image, ImageTk
                    img = Image.open(path)
                    logo_img = ImageTk.PhotoImage(img)
                except Exception:
                    logo_img = None
            if logo_img:
                self.label_logo.config(image=logo_img, text="")
                self.label_logo.image = logo_img 

        # Label Email (row 1, col 0)
        self.label_email = ttk.Label(self.painel_principal, text="Email:", style='Label.TLabel')
        self.label_email.grid(row=1, column=0, sticky="e", padx=(0, 12), pady=6)

        # TextField Email (row 1, col 1-2)
        self.text_field_email = ttk.Entry(self.painel_principal, font=("Segoe UI", 12))
        self.text_field_email.grid(row=1, column=1, columnspan=2, sticky="ew", padx=(0, 10), pady=6)

        # Label Senha (row 2, col 0)
        self.label_senha = ttk.Label(self.painel_principal, text="Senha:", style='Label.TLabel')
        self.label_senha.grid(row=2, column=0, sticky="e", padx=(0, 12), pady=6)

        # PasswordField Senha (row 2, col 1-2)
        self.password_field_senha = ttk.Entry(self.painel_principal, show="*", font=("Segoe UI", 12))
        self.password_field_senha.grid(row=2, column=1, columnspan=2, sticky="ew", padx=(0, 10), pady=6)

        # Label Tipo (row 3, col 0)
        self.label_tipo = ttk.Label(self.painel_principal, text="Tipo", style='Label.TLabel')
        self.label_tipo.grid(row=3, column=0, sticky="e", padx=(0, 12), pady=6)

        # ComboBox Tipo (row 3, col 1)
        self.combo_box_tipo = ttk.Combobox(self.painel_principal, values=["Adotante", "Protetor", "Admin"], state="readonly", font=("Segoe UI", 12))
        self.combo_box_tipo.current(0)  # Selecionar primeiro por padrão
        self.combo_box_tipo.grid(row=3, column=1, sticky="ew", padx=(0, 10), pady=6)

        # Spacer (row 4, col 0) matching card background (used for alignment)
        spacer = ttk.Frame(self.painel_principal, style='Card.TFrame', width=20)
        spacer.grid(row=4, column=0, sticky="ew", padx=(0, 10))

        # Button Login (row 4, col 1-2) with softer style
        self.button_login = ttk.Button(self.painel_principal, text="Entrar", style='Accent.TButton', command=self.realizar_login)
        self.button_login.grid(row=4, column=1, columnspan=2, sticky="ew", padx=(0, 10), pady=(18, 0))

        # Make inputs expand nicely
        self.painel_principal.grid_columnconfigure(1, weight=1)
        self.painel_principal.grid_columnconfigure(2, weight=1)

    def realizar_login(self):
        email = self.text_field_email.get()
        senha = self.password_field_senha.get()

        if not email or not senha:
            messagebox.showwarning("Campos vazios", "Por favor, preencha todos os campos!")
            return

        tipo_selecionado = self.combo_box_tipo.get()

        try:
            login_dao = LoginDAO()

            if tipo_selecionado == "Adotante":
                adotante = login_dao.loginAdotante(email, senha)
                if adotante:
                    messagebox.showinfo("Sucesso", "Login realizado com sucesso como Adotante!")
                    self.controller.show_frame("Welcome", tipoUsuario="Adotante", usuario=adotante)
                    return
            elif tipo_selecionado == "Protetor":
                protetor = login_dao.loginProtetor(email, senha)
                if protetor:
                    messagebox.showinfo("Sucesso", "Login realizado com sucesso como Protetor!")
                    self.controller.show_frame("Welcome", tipoUsuario="Protetor", usuario=protetor)
                    return
            elif tipo_selecionado == "Admin":
                cursor = MYSQLConnection().get_connection().cursor()
                sql = "SELECT * FROM admin WHERE email = %s AND senha = %s"
                cursor.execute(sql,(email, senha))
                admin = cursor.fetchone()
                if admin:
                    messagebox.showinfo("Sucesso", "Login realizado com sucesso como Admin!")
                    self.controller.show_frame("Admin")
                    return
                else:
                    messagebox.showerror("Erro de Login", "Email ou senha incorretos para o tipo selecionado!")
        except CustomException as e:
            messagebox.showerror("Erro", f"Erro ao realizar login: {e}")
        finally:
            cursor.close()

