from enum import Enum

class StatusProcesso(Enum):
    RASCUNHO = "RASCUNHO"
    SUBMETIDO = "SUBMETIDO"
    TRIAGEM = "TRIAGEM"
    ENTREVISTA = "ENTREVISTA"
    VISITA_DOMICILIAR = "VISITA_DOMICILIAR"
    APROVADO = "APROVADO"
    CONTRATO = "CONTRATO"
    CONCLUIDO = "CONCLUIDO"
    POS_ADOCAO = "POS_ADOCAO"
    ENCERRADO = "ENCERRADO"