# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk
from tkinter import ttk, messagebox

# Adicionar o diretório raiz do projeto ao sys.path para importar módulos
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from DAO.login_dao import LoginDAO
from schemas.adotante import Adotante
from schemas.protetor import Protetor
from exceptions.custom_exception import CustomException

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

class Login(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Sistema de Adoção Animal - Login")
        self.geometry("450x400")
        self.resizable(False, False)

        # Painel principal
        self.painel_principal = tk.Frame(self, bg="#A0A0A0")  # Cinza
        self.painel_principal.pack(fill=tk.BOTH, expand=True)

        # Label logo
        self.label_logo = tk.Label(self.painel_principal, text="Logo", bg="#A0A0A0", font=("Arial", 24))
        self.label_logo.pack(pady=20)

        # Carregar logo se existir
        logo_img = None
        for fname in ("logo.png", "logo.jpg", "logo.gif", "logo.bmp"):
            path = load_asset(fname)
            if os.path.exists(path):
                try:
                    if fname.lower().endswith(('.png', '.gif')):
                        logo_img = tk.PhotoImage(file=path)
                    else:
                        try:
                            from PIL import Image, ImageTk
                            img = Image.open(path)
                            logo_img = ImageTk.PhotoImage(img)
                        except ImportError:
                            logo_img = None
                except Exception:
                    logo_img = None
            if logo_img:
                self.label_logo.config(image=logo_img, text="")
                self.label_logo.image = logo_img  # Manter referência
                break

        # Label Email
        self.label_email = tk.Label(self.painel_principal, text="E-mail", bg="#A0A0A0", fg="black", font=("Arial", 12))
        self.label_email.pack(pady=(10, 0))

        # TextField Email
        self.text_field_email = tk.Entry(self.painel_principal, bg="white", font=("Arial", 12))
        self.text_field_email.pack(pady=(0, 10), padx=20, fill=tk.X)

        # Label Senha
        self.label_senha = tk.Label(self.painel_principal, text="Senha", bg="#A0A0A0", fg="black", font=("Arial", 12))
        self.label_senha.pack(pady=(10, 0))

        # PasswordField Senha
        self.password_field_senha = tk.Entry(self.painel_principal, bg="white", show="*", font=("Arial", 12))
        self.password_field_senha.pack(pady=(0, 10), padx=20, fill=tk.X)

        # ComboBox Tipo
        self.combo_box_tipo = ttk.Combobox(self.painel_principal, values=["Adotante", "Protetor"], state="readonly", font=("Arial", 12))
        self.combo_box_tipo.current(0)  # Selecionar primeiro por padrão
        self.combo_box_tipo.pack(pady=(10, 20), padx=20, fill=tk.X)

        # Button Login
        self.button_login = tk.Button(self.painel_principal, text="Entrar", bg="#4169E1", fg="white", font=("Arial", 14, "bold"), command=self.realizar_login)
        self.button_login.pack(pady=(0, 20), padx=20, fill=tk.X)

    def realizar_login(self):
        email = self.text_field_email.get()
        senha = self.password_field_senha.get()

        if not email or not senha:
            messagebox.showwarning("Campos vazios", "Por favor, preencha todos os campos!")
            return

        tipo_selecionado = self.combo_box_tipo.get()

        try:
            login_dao = LoginDAO()

            if tipo_selecionado == "Adotante":
                adotante = login_dao.loginAdotante(email, senha)
                if adotante:
                    messagebox.showinfo("Sucesso", "Login realizado com sucesso como Adotante!")
                    self.destroy()
                    # Aqui você pode abrir a próxima tela, ex: Welcome("Adotante", adotante)
                    return
            elif tipo_selecionado == "Protetor":
                protetor = login_dao.loginProtetor(email, senha)
                if protetor:
                    messagebox.showinfo("Sucesso", "Login realizado com sucesso como Protetor!")
                    self.destroy()
                    # Aqui você pode abrir a próxima tela, ex: Welcome("Protetor", protetor)
                    return

            messagebox.showerror("Erro de Login", "Email ou senha incorretos para o tipo selecionado!")

        except CustomException as e:
            messagebox.showerror("Erro", f"Erro ao realizar login: {e}")

if __name__ == "__main__":
    app = Login()
    app.mainloop()
