from DAO.adocao_dao import AdocaoDAO
from DAO.processo_adocao_dao import ProcessoAdocaoDAO
from DAO.suport_pos_adocao_dao import SuportePosAdocaoDAO
from DAO.animal_dao import AnimalDAO
from DAO.adotante_dao import AdotanteDAO
from DAO.mensagem_dao import MensagemDAO
from DAO.etapa_processo_dao import EtapaProcessoDAO
from DAO.login_dao import LoginDAO
from DAO.protetor_dao import ProtetorDAO
from DAO.foto_animal_dao import FotoAnimalDAO
from DAO.chat_dao import ChatDAO