from .adocao_dao import AdocaoDAO
from .processo_adocao_dao import ProcessoAdocaoDAO
from .suport_pos_adocao_dao import SuportePosAdocaoDAO
from .animal_dao import AnimalDAO
from .adotante_dao import AdotanteDAO
from .mensagem_dao import MensagemDAO
from .etapa_processo_dao import EtapaProcessoDAO
from .login_dao import LoginDAO
from .protetor_dao import ProtetorDAO
from .foto_animal_dao import FotoAnimalDAO
from .chat_dao import ChatDAO